In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
list1=['a','b','c','d']
a=np.array(list1)
print(a)

['a' 'b' 'c' 'd']


In [5]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
arr=np.array(23)
print(arr)

23


In [7]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [8]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[12,34,56,0],[34,23,20,4]]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[12 34 56  0]
  [34 23 20  4]]]


In [14]:
import numpy as np
a=np.array(23) #0D
b=np.array([1,2,3,4]) #1D
c=np.array([[1,2,3,4],[5,6,7,8]]) #2D
d=np.array([[[1,2,3,4],[5,6,7,8]],[[12,34,56,0],[34,23,20,3]]]) #3D

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [20]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[-2])

4


In [21]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[-2]+arr[1])

6


In [23]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print('2nd element on 1st row:',arr[0,2])

2nd element on 1st row: 3


In [24]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,1]-arr[1,2])

-5


In [27]:
import numpy as np
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[12,34,56,0],[34,23,20,4]]])
print(arr[0,1,3])

8


In [31]:
import numpy as np
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[12,34,56,0],[34,23,20,4]]])
print(arr[0,1,3]+arr[0,1,2])

15


In [40]:
import numpy as np
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[12,34,56,5],[34,23,20,4]]])
print(arr[0,0,3]+arr[0,1,3]+arr[1,0,3]+arr[1,1,3])


21
